block_cipher = None
a = Analysis(
    ['HelloToolbelt.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('eligibility_tool.py', '.'),
        ('configurator_tool.py', '.'),
        ('multisearch_tool.py', '.'),
        ('Cron_tool.py', '.'),
        ('Base64_Tool.py', '.'),
        ('DLQ_Tool.py', '.'),
        ('bill_hunter.py', '.'),  # Added Bill Hunter tool
        ('shipping_map.py', '.'),
        ('Icon.icns', '.'),
    ],
    hiddenimports=[
        'eligibility_tool',
        'configurator_tool', 
        'multisearch_tool',
        'Cron_tool',
        'Base64_Tool',
        'DLQ_Tool',
        'bill_hunter',  # Added Bill Hunter hidden import
        'shipping_map',
        'pandas',
        'openpyxl',
        'dateutil',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        '_tkinter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MultiToolSuite',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
app = BUNDLE(
    exe,
    name='HelloToolBelt.app',
    icon='Icon.icns',
    bundle_identifier=None,
)